# Automatically generated by pb2py
# fmt: off
import protobuf as p


class BytecoinGenerateOutputSeedResponse(p.MessageType):
    MESSAGE_WIRE_TYPE = 808

    def __init__(
        self,
        output_seed: bytes = None,
    ) -> None:
        self.output_seed = output_seed

    @classmethod
    def get_fields(cls):
        return {
            1: ('output_seed', p.BytesType, 0),
        }
