# Automatically generated by pb2py
# fmt: off
import protobuf as p


class BytecoinSignStepBResponse(p.MessageType):
    MESSAGE_WIRE_TYPE = 826

    def __init__(
        self,
        my_rr: bytes = None,
        rs: bytes = None,
        ra: bytes = None,
        encryption_key: bytes = None,
    ) -> None:
        self.my_rr = my_rr
        self.rs = rs
        self.ra = ra
        self.encryption_key = encryption_key

    @classmethod
    def get_fields(cls):
        return {
            1: ('my_rr', p.BytesType, 0),
            2: ('rs', p.BytesType, 0),
            3: ('ra', p.BytesType, 0),
            4: ('encryption_key', p.BytesType, 0),
        }
