# Automatically generated by pb2py
# fmt: off
import protobuf as p


class BytecoinExportViewWalletResponse(p.MessageType):
    MESSAGE_WIRE_TYPE = 810

    def __init__(
        self,
        audit_key_base_secret_key: bytes = None,
        view_secret_key: bytes = None,
        view_seed: bytes = None,
        view_secrets_signature: bytes = None,
    ) -> None:
        self.audit_key_base_secret_key = audit_key_base_secret_key
        self.view_secret_key = view_secret_key
        self.view_seed = view_seed
        self.view_secrets_signature = view_secrets_signature

    @classmethod
    def get_fields(cls):
        return {
            1: ('audit_key_base_secret_key', p.BytesType, 0),
            2: ('view_secret_key', p.BytesType, 0),
            3: ('view_seed', p.BytesType, 0),
            4: ('view_secrets_signature', p.BytesType, 0),
        }
