# Automatically generated by pb2py
# fmt: off
import protobuf as p

if __debug__:
    try:
        from typing import List
    except ImportError:
        List = None  # type: ignore


class BytecoinScanOutputsRequest(p.MessageType):
    MESSAGE_WIRE_TYPE = 803

    def __init__(
        self,
        output_public_key: List[bytes] = None,
    ) -> None:
        self.output_public_key = output_public_key if output_public_key is not None else []

    @classmethod
    def get_fields(cls):
        return {
            1: ('output_public_key', p.BytesType, p.FLAG_REPEATED),
        }
