# Automatically generated by pb2py
# fmt: off
import protobuf as p


class BytecoinSignAddOutputResponse(p.MessageType):
    MESSAGE_WIRE_TYPE = 816

    def __init__(
        self,
        public_key: bytes = None,
        encrypted_secret: bytes = None,
        encrypted_address_type: int = None,
    ) -> None:
        self.public_key = public_key
        self.encrypted_secret = encrypted_secret
        self.encrypted_address_type = encrypted_address_type

    @classmethod
    def get_fields(cls):
        return {
            1: ('public_key', p.BytesType, 0),
            2: ('encrypted_secret', p.BytesType, 0),
            3: ('encrypted_address_type', p.UVarintType, 0),
        }
