# Automatically generated by pb2py
# fmt: off
import protobuf as p

if __debug__:
    try:
        from typing import List
    except ImportError:
        List = None  # type: ignore


class BytecoinScanOutputsResponse(p.MessageType):
    MESSAGE_WIRE_TYPE = 804

    def __init__(
        self,
        Pv: List[bytes] = None,
    ) -> None:
        self.Pv = Pv if Pv is not None else []

    @classmethod
    def get_fields(cls):
        return {
            1: ('Pv', p.BytesType, p.FLAG_REPEATED),
        }
