# Automatically generated by pb2py
# fmt: off
import protobuf as p


class BytecoinSignGetC0Response(p.MessageType):
    MESSAGE_WIRE_TYPE = 824

    def __init__(
        self,
        c0: bytes = None,
    ) -> None:
        self.c0 = c0

    @classmethod
    def get_fields(cls):
        return {
            1: ('c0', p.BytesType, 0),
        }
