# Automatically generated by pb2py
# fmt: off
import protobuf as p


class BytecoinStartResponse(p.MessageType):
    MESSAGE_WIRE_TYPE = 802

    def __init__(
        self,
        version: bytes = None,
        wallet_key: bytes = None,
        A_plus_sH: bytes = None,
        v_mul_A_plus_sH: bytes = None,
        view_public_key: bytes = None,
    ) -> None:
        self.version = version
        self.wallet_key = wallet_key
        self.A_plus_sH = A_plus_sH
        self.v_mul_A_plus_sH = v_mul_A_plus_sH
        self.view_public_key = view_public_key

    @classmethod
    def get_fields(cls):
        return {
            1: ('version', p.BytesType, 0),
            2: ('wallet_key', p.BytesType, 0),
            3: ('A_plus_sH', p.BytesType, 0),
            4: ('v_mul_A_plus_sH', p.BytesType, 0),
            5: ('view_public_key', p.BytesType, 0),
        }
