# Automatically generated by pb2py
# fmt: off
import protobuf as p


class BytecoinSignStepAResponse(p.MessageType):
    MESSAGE_WIRE_TYPE = 820

    def __init__(
        self,
        sig_p: bytes = None,
        y: bytes = None,
        z: bytes = None,
    ) -> None:
        self.sig_p = sig_p
        self.y = y
        self.z = z

    @classmethod
    def get_fields(cls):
        return {
            1: ('sig_p', p.BytesType, 0),
            2: ('y', p.BytesType, 0),
            3: ('z', p.BytesType, 0),
        }
