# Automatically generated by pb2py
# fmt: off
import protobuf as p


class BytecoinGenerateKeyimageResponse(p.MessageType):
    MESSAGE_WIRE_TYPE = 806

    def __init__(
        self,
        keyimage: bytes = None,
    ) -> None:
        self.keyimage = keyimage

    @classmethod
    def get_fields(cls):
        return {
            1: ('keyimage', p.BytesType, 0),
        }
