# Automatically generated by pb2py
# fmt: off
import protobuf as p


class BytecoinSignStepBRequest(p.MessageType):
    MESSAGE_WIRE_TYPE = 825

    def __init__(
        self,
        output_secret_hash_arg: bytes = None,
        address_index: int = None,
        my_c: bytes = None,
    ) -> None:
        self.output_secret_hash_arg = output_secret_hash_arg
        self.address_index = address_index
        self.my_c = my_c

    @classmethod
    def get_fields(cls):
        return {
            1: ('output_secret_hash_arg', p.BytesType, 0),
            2: ('address_index', p.UVarintType, 0),
            3: ('my_c', p.BytesType, 0),
        }
