# Automatically generated by pb2py
# fmt: off
import protobuf as p


class BytecoinGenerateOutputSeedRequest(p.MessageType):
    MESSAGE_WIRE_TYPE = 807

    def __init__(
        self,
        tx_inputs_hash: bytes = None,
        out_index: int = None,
    ) -> None:
        self.tx_inputs_hash = tx_inputs_hash
        self.out_index = out_index

    @classmethod
    def get_fields(cls):
        return {
            1: ('tx_inputs_hash', p.BytesType, 0),
            2: ('out_index', p.UVarintType, 0),
        }
