# Automatically generated by pb2py
# fmt: off
import protobuf as p


class BytecoinSignAddOutputRequest(p.MessageType):
    MESSAGE_WIRE_TYPE = 815

    def __init__(
        self,
        change: bool = None,
        amount: int = None,
        dst_address_tag: int = None,
        dst_address_S: bytes = None,
        dst_address_Sv: bytes = None,
        change_address_index: int = None,
    ) -> None:
        self.change = change
        self.amount = amount
        self.dst_address_tag = dst_address_tag
        self.dst_address_S = dst_address_S
        self.dst_address_Sv = dst_address_Sv
        self.change_address_index = change_address_index

    @classmethod
    def get_fields(cls):
        return {
            1: ('change', p.BoolType, 0),
            2: ('amount', p.UVarintType, 0),
            3: ('dst_address_tag', p.UVarintType, 0),
            4: ('dst_address_S', p.BytesType, 0),
            5: ('dst_address_Sv', p.BytesType, 0),
            6: ('change_address_index', p.UVarintType, 0),
        }
