# Automatically generated by pb2py
# fmt: off
import protobuf as p


class BytecoinSignAddExtraRequest(p.MessageType):
    MESSAGE_WIRE_TYPE = 817

    def __init__(
        self,
        extra_chunk: bytes = None,
    ) -> None:
        self.extra_chunk = extra_chunk

    @classmethod
    def get_fields(cls):
        return {
            1: ('extra_chunk', p.BytesType, 0),
        }
